verbose errors & incremental displays

diff --git a/koala b/koala
--- a/koala
+++ b/koala
@@ -1,7 +1,9 @@
 #!/bin/bash
 [ -z "$chrome" ] && chrome="chromium"
-pids=
-destinations=
+
+pid_array=()
+destination_array=()
+display_array=()
 out="/dev/null"
 
 # get options
@@ -13,22 +15,34 @@ esac; shift; done
 if [[ "$1" == '--' ]]; then shift; fi
 
 _end() {
-    kill $pids 2> $out
+    kill "${pid_array[@]}" 2> $out
     reset
     [[ -z $1 ]] && echo -e "\e[31mShutting down Koala...\e[0m" && exit 0
-    [[ $1 == 1 ]] && echo -e "\e[31m$2 is missing required values.\e[0m" && exit 1
+    [[ $1 == 1 ]] && echo -e "\e[31m$2 is missing required value: $3\e[0m" && exit 1
     [[ $1 == 2 ]] && echo -e "\e[31m$2 contains a duplicate destination.\e[0m" && exit 2
     exit 127
 }
+
+trap _end INT
 
 newline_check() {
     [[ $(tail -c1 "$1" | wc -l) -gt 0 ]]
 }
 
-trap _end INT
+displays_check() {
+    for i in ${display_array[@]}; do
+        [ $i == $1 ] && return 0
+    done
+    return 1
+}
 
 create_stream() {
-    local DISPLAY=:`shuf -i 99-999999999 -n1`
+    local display_num=1000
+    while displays_check $display_num; do
+        ((display_num+=1))
+    done
+    display_array+=($display_num)
+    DISPLAY=:$display_num
     local width=1920
     local height=1080
     local colordepth=24
@@ -44,17 +58,19 @@ create_stream() {
         local "$line"
     done < "$1"
 
-    [[ -z "$name" || -z "$webpage" || -z "$destination" ]] && _end 1 $1
+    [[ -z "$name" ]] && _end 1 $1 name
+    [[ -z "$webpage" ]] && _end 1 $1 webpage
+    [[ -z "$destination" ]] && _end 1 $1 destination
 
     # check for duplicate destinations
-    for i in $destinations; do
+    for i in ${destination_array[@]}; do
         [ $i == $destination ] && _end 2 $1
     done
 
-    destinations="$destinations $destination"
+    destination_array+=($destination)
 
     Xvfb ${DISPLAY} -screen 0 ${width}x${height}x${colordepth} &
-    pids="$! $pids"
+    pid_array+=($!)
 
     DISPLAY=$DISPLAY ${chrome} \
         --user-data-dir=$(mktemp -d) \
@@ -63,7 +79,7 @@ create_stream() {
         --window-position=0,0 \
         --window-size=${width},${height} \
         ${webpage} 2> $out &
-    pids="$! $pids"
+    pid_array+=($!)
 
     ffmpeg \
         -video_size ${width}x${height} \
@@ -76,9 +92,9 @@ create_stream() {
         -b:v ${bitrate}k \
         -f mpegts \
         udp://${destination} 2> $out &
-    pids="$! $pids"
+    pid_array+=($!)
 
-    echo -e "\e[36m[${name}]: \e[0mStreaming to \e[34mudp://${destination}\e[0m @ \e[33m${width}x${height}x${colordepth}\e[0m"
+    echo -e "\e[36m[${name}]: \e[0mStreaming to \e[34mudp://${destination}\e[0m @ \e[33m${width}x${height}x${colordepth}\e[0m (${DISPLAY})"
     echo -e "URL: \e[32m${webpage}\e[0m"
 }
 
