catch errors

diff --git a/koala b/koala
--- a/koala
+++ b/koala
@@ -1,12 +1,15 @@
 #!/bin/bash
-[ -z $chrome ] && chrome="chromium"
+[ -z "$chrome" ] && chrome="chromium"
 pids=
+destinations=
 
 _end() {
-    echo -e "\e[31mShutting down Koala...\e[0m"
+    stty sane
     kill $pids 2> /dev/null
-    reset
-    exit 0
+    [[ -z $1 ]] && echo -e "\e[31mShutting down Koala...\e[0m" && exit 0
+    [[ $1 == 1 ]] && echo -e "\e[31m$2 is missing required values.\e[0m" && exit 1
+    [[ $1 == 2 ]] && echo -e "\e[31m$2 contains a duplicate destination.\e[0m" && exit 2
+    exit 127
 }
 
 trap _end INT
@@ -27,6 +30,14 @@ create_stream() {
         [[ $line == \#* ]] && continue
         local "$line"
     done < "$1"
+
+    [[ -z "$name" || -z "$webpage" || -z "$webpage" ]] && _end 1 $1
+
+    for i in $destinations; do
+        [ $i == $destination ] && _end 2 $1
+    done
+
+    destinations="$destinations $destination"
 
     Xvfb ${DISPLAY} -screen 0 ${width}x${height}x${colordepth} &
     pids="$! $pids"
@@ -50,10 +61,10 @@ create_stream() {
         -i ${DISPLAY} \
         -b:v ${bitrate}k \
         -f mpegts \
-        udp://${destination}:${port} 2> /dev/null &
+        udp://${destination} 2> /dev/null &
     pids="$! $pids"
 
-    echo -e "\e[36m[${name}]: \e[0mStreaming to \e[34mudp://${destination}:${port}\e[0m @ \e[33m${width}x${height}\e[0m on display ${DISPLAY}"
+    echo -e "\e[36m[${name}]: \e[0mStreaming to \e[34mudp://${destination}:${port}\e[0m @ \e[33m${width}x${height}x${colordepth}\e[0m"
     echo -e "URL: \e[32m${webpage}\e[0m"
 }
 
